const cases = [
    
    {
        id: 1,
        patientName: 'Aisha Perera',
        healthIssue: 'Renal Dialysis',
        isurgent: true, 
        goal: 500000,
        raised: 150000,
        address: 'Colombo, LK',
        postedDate: '2025-10-01',
        contactPhone: '071XXXXXXX',
        contactEmail: 'aisha@example.com',
        description: 'Aisha needs urgent funding for her life-saving kidney dialysis treatments.',
    },
    {
        id: 2,
        patientName: 'Ravi Kumara',
        healthIssue: 'Heart Surgery',
        isurgent: false, 
        goal: 1200000,
        raised: 800000,
        address: 'Galle, LK',
        postedDate: '2025-09-15',
        contactPhone: '077XXXXXXX',
        contactEmail: 'ravi@example.com',
        description: "Ravi Kumara, a 35-year-old father of two, faces a critical health battle against a severe congenital cardiac defect that requires immediate open-heart surgery. This complex operation is essential to correct a structural anomaly in his heart that has caused progressive failure and makes even simple daily tasks a struggle. Without this procedure, Ravi's life expectancy is severely limited. The LKR 1,200,000 goal covers the surgical team fees, necessary imported medical equipment, and the extensive post-operative care required in the Intensive Care Unit (ICU). Every contribution to this fund is a critical investment in Ravi's future and his family’s stability.",
    },
    {
        id: 3,
        patientName: 'Samanthi Silva',
        healthIssue: 'Cancer Treatment',
        isurgent: true, 
        goal: 850000,
        raised: 5000,
        address: 'Kandy, LK',
        postedDate: '2025-11-20',
        contactPhone: '076XXXXXXX',
        contactEmail: 'samanthi@example.com',
        description: 'Samanthi is a mother of two and requires chemotherapy sessions to fight breast cancer.',
    },

    
    {
        id: 4,
        patientName: 'Nimal Fernando',
        healthIssue: 'Spinal Cord Injury Rehab',
        isurgent: false,
        goal: 700000,
        raised: 400000,
        address: 'Negombo, LK',
        postedDate: '2025-11-10',
        contactPhone: '071XXXXXX1',
        contactEmail: 'nimal@example.com',
        description: 'Nimal needs extended rehabilitation after a serious accident to regain mobility.',
    },
    {
        id: 5,
        patientName: 'Lalitha Devi',
        healthIssue: 'Critical Burn Care',
        isurgent: true,
        goal: 1500000,
        raised: 25000,
        address: 'Jaffna, LK',
        postedDate: '2025-11-22',
        contactPhone: '077XXXXXX2',
        contactEmail: 'lalitha@example.com',
        description: 'Lalitha sustained severe burns and requires multiple skin graft surgeries immediately.',
    },
    {
        id: 6,
        patientName: 'Kamal Wijesinghe',
        healthIssue: 'Prosthetic Limb',
        isurgent: false,
        goal: 300000,
        raised: 300000, // Fully funded
        address: 'Matara, LK',
        postedDate: '2025-09-05',
        contactPhone: '076XXXXXX3',
        contactEmail: 'kamal@example.com',
        description: 'Kamal needs funds to acquire a modern prosthetic leg for independence.',
    },
    {
        id: 7,
        patientName: 'Anusha Ranasinghe',
        healthIssue: 'Liver Transplant',
        isurgent: true,
        goal: 4000000,
        raised: 1500000,
        address: 'Kandy, LK',
        postedDate: '2025-11-15',
        contactPhone: '071XXXXXX4',
        contactEmail: 'anusha@example.com',
        description: 'Anusha requires a life-saving liver transplant in the next three months.',
    },
    {
        id: 8,
        patientName: 'Tharindu Ekanayake',
        healthIssue: 'Cataract Surgery',
        isurgent: false,
        goal: 80000,
        raised: 10000,
        address: 'Kurunegala, LK',
        postedDate: '2025-10-25',
        contactPhone: '077XXXXXX5',
        contactEmail: 'tharindu@example.com',
        description: 'Tharindu needs bilateral cataract surgery to prevent blindness.',
    },
    {
        id: 9,
        patientName: 'Priya Samarawickrama',
        healthIssue: 'Chemotherapy Support',
        isurgent: true,
        goal: 600000,
        raised: 550000,
        address: 'Gampaha, LK',
        postedDate: '2025-11-01',
        contactPhone: '076XXXXXX6',
        contactEmail: 'priya@example.com',
        description: 'Priya is undergoing intensive chemotherapy and needs funds for medication.',
    },
    {
        id: 10,
        patientName: 'Vimal Hewage',
        healthIssue: 'Orthopedic Surgery',
        isurgent: false,
        goal: 450000,
        raised: 0,
        address: 'Nuwara Eliya, LK',
        postedDate: '2025-11-23',
        contactPhone: '071XXXXXX7',
        contactEmail: 'vimal@example.com',
        description: 'Vimal requires urgent corrective surgery for a complex knee fracture.',
    },
    {
        id: 11,
        patientName: 'Shiromi Pathirana',
        healthIssue: 'Bone Marrow Transplant',
        isurgent: true,
        goal: 9000000,
        raised: 800000,
        address: 'Colombo, LK',
        postedDate: '2025-11-05',
        contactPhone: '077XXXXXX8',
        contactEmail: 'shiromi@example.com',
        description: 'Shiromi, a young girl, urgently needs a bone marrow transplant to survive leukemia.',
    },
    {
        id: 12,
        patientName: 'Chandana Rupasinghe',
        healthIssue: 'Pediatric Cardiac Care',
        isurgent: false,
        goal: 1100000,
        raised: 100000,
        address: 'Ampara, LK',
        postedDate: '2025-10-10',
        contactPhone: '076XXXXXX9',
        contactEmail: 'chandana@example.com',
        description: 'Fundraising for corrective heart procedures for infant Chandana.',
    },
    {
        id: 13,
        patientName: 'Sunil Dias',
        healthIssue: 'Dialysis Treatment',
        isurgent: true,
        goal: 250000,
        raised: 100000,
        address: 'Kalutara, LK',
        postedDate: '2025-11-24',
        contactPhone: '071XXXXX10',
        contactEmail: 'sunil@example.com',
        description: 'Sunil requires ongoing dialysis sessions which are not covered by insurance.',
    },
    {
        id: 14,
        patientName: 'Iresha ',
        healthIssue: 'Dental Reconstruction',
        isurgent: false,
        goal: 180000,
        raised: 10000,
        address: 'Kandy, LK',
        postedDate: '2025-09-01',
        contactPhone: '077XXXXX11',
        contactEmail: 'iresha@example.com',
        description: 'Iresha needs extensive dental reconstruction following a childhood illness.',
    },
    {
        id: 15,
        patientName: 'Heshan Gunaratne',
        healthIssue: 'Rehabilitation & Equipment',
        isurgent: true,
        goal: 350000,
        raised: 300000,
        address: 'Galle, LK',
        postedDate: '2025-11-18',
        contactPhone: '076XXXXX12',
        contactEmail: 'heshan@example.com',
        description: 'Heshan requires a specialized wheelchair and continuous physiotherapy support.',
    },
];

export default cases;